name: yume
services:
  yume:
    build: .
    command: ["npm", "run", "prod:start"]
    container_name: yume
    environment:
      - DISCORD_BOT_TOKEN=YOUR_DISCORD_BOT_TOKEN
      - DISCORD_BOT_CLIENT_ID=YOUR_DISCORD_APPLICATION_ID
      - ANIME_SCHEDULE_API_TOKEN=YOUR_ANIMESCHEDULE_API_TOKEN
    volumes:
      - ./data:/app/data
    image: ghcr.io/macluxhd/yume:latest